export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Navegador
        document: "readonly",
        window: "readonly",
        localStorage: "readonly",
        history: "readonly",
        location: "readonly",
        console: "readonly",
        URLSearchParams: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        fetch: "readonly",
        // Leaflet
        L: "readonly",
        // Scripts clásicos: identificadores compartidos entre archivos.
        // Se declaran aquí porque el estado vive en el ámbito global de core.js
        // y los demás scripts lo leen (patrón "script clásico" para file://).
        CENTER: "readonly",
        ZOOM: "readonly",
        SHIELD_ICON_SVG: "readonly",
        PIN_ICON_SVG: "readonly",
        colorForIndex: "readonly",
        colorForText: "readonly",
        municipioColors: "readonly",
        municipiosLayer: "readonly",
        parroquiasLayer: "readonly",
        markersLayer: "readonly",
        municipiosGeoData: "readonly",
        activeMunicipios: "readonly",
        activeParroquias: "readonly",
        activeTipos: "readonly",
        allParroquiaFeatures: "readonly",
        allMarkers: "readonly",
        highlightedParroquias: "readonly",
        lastUpdated: "readonly",
        markersLoadFailed: "readonly",
        currentLayout: "readonly",
        heatLayer: "readonly",
        heatEnabled: "readonly",
        riskZones: "readonly",
        timeAgo: "readonly",
        pointInRing: "readonly",
        pointInPolygonRings: "readonly",
        municipioForPoint: "readonly",
        ensureMarkerMunicipios: "readonly",
        normalizeText: "readonly",
        hasValue: "readonly",
        prettifyLabel: "readonly",
        escapeHtml: "readonly",
        fetchJSON: "readonly",
        HEATMAP_DATASETS: "readonly",
        currentHeatRadius: "readonly",
        heatOptionsForRadius: "readonly",
        buildIcon: "readonly",
        currentMarkerSize: "readonly",
        clusteringEnabled: "readonly",
        map: "readonly",
        parroquiaBaseStyle: "readonly",
        PARROQUIA_HIGHLIGHT_STYLE: "readonly",
        PARROQUIA_HOVER_STYLE: "readonly",
        createMarkersLayer: "readonly",
        rebuildMarkersLayer: "readonly",
        buildEntityCardHtml: "readonly",
        openDetailPanel: "readonly",
        closeDetailPanel: "readonly",
        updateStatusBar: "readonly",
        loadHeatmapDataset: "readonly",
        buildMunicipioFilterList: "readonly",
        buildParroquiaFilterList: "readonly",
        buildTipoFilterList: "readonly",
        filterParroquiaList: "readonly",
        applyFilter: "readonly",
        applyMarkerFilter: "readonly",
        selectParroquia: "readonly",
        findParroquiaLayer: "readonly",
        clearSelection: "readonly",
        updateInfoPanel: "readonly",
        saveStateToUrl: "readonly",
        applyUrlState: "readonly",
        currentTheme: "readonly",
        applyTheme: "readonly",
        applyLayoutUI: "readonly",
        syncLayersForLayout: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
      eqeqeq: "warn",
      curly: "warn",
      "prefer-const": "warn",
      "no-var": "error",
    },
  },
];